iRO-Suit/src/main/java/br/com/irosuit/entity/Item.java
package br.com.irosuit.entity;

/**
 *
 * @author jose.bonifacio
 */
public class Item {
    
    private String name;
    private String value;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
    
}

iRO-Suit/src/main/java/br/com/irosuit/IndexController.java
package br.com.irosuit;

import br.com.irosuit.entity.Item;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author jose.bonifacio
 */
@Named
@ViewScoped
public class IndexController implements Serializable {

    private List<Item> items;

    public List<Item> getTest() {
        if (items == null) {
            try {
                Document doc = Jsoup.connect("http://ragial.com/search/iRO-Renewal/morrigane").get();
                Elements listLines = doc.select(".ilist tr");
                items = new ArrayList<>();
                for (Element line : listLines) {
                    Item item = new Item();
                    boolean isAvailable = false;
                    for (Element lineChildren : line.getAllElements()) {
                        if (lineChildren.className().equals("name")) {
                            for (Element nameColumnChildren : lineChildren.getAllElements()) {
                                if (nameColumnChildren.className().contains("activate_tr")) {
                                    isAvailable = true;
                                    break;
                                }
                            }
                            if (isAvailable) {
                                item.setName(lineChildren.text());
                            }
                        }
                        if (isAvailable) {
                            if (lineChildren.className().contains("price")) {
                                item.setValue(lineChildren.text());
                            }
                        }
                    }
                    items.add(item);
                }
            } catch (IOException ex) {
                Logger.getLogger(IndexController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return items;
    }
}

iRO-Suit/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head id="header">
        <title>iRO Suit</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <meta name="author" content="http://www.facebook.com/jose.bonifacio.5"></meta>
        <h:outputStylesheet library="font-awesome" name="css/font-awesome.min.css"></h:outputStylesheet>
        <h:outputScript library="javascript" name="jquery-2.2.0.min.js"></h:outputScript>
        <h:outputScript library="javascript" name="jquery-ui.min.js"></h:outputScript>
        <f:facet name="no-fa">true</f:facet>
    </h:head>
    <h:body>
        <h:form>
            <h:dataTable value="#{indexController.test}" var="test">
                <h:column>
                    <h:outputText value="#{test.name}"/>
                </h:column>
                <h:column>
                    <h:outputText value="#{test.value}"/>
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>